#!/bin/bash

set -euo pipefail

IMG_NAME=wmfmariadbpy-integration
VOL_NAME=wmfmariadbpy-vol

cd $(dirname "$0")

[ -d "cache" ] || mkdir "cache"

get_mariadb() {
    local version="${1:?}"
    local target="cache/mariadb-${version}-linux-x86_64.tar.gz"

    [ -e "$target" ] && return

    echo "====> Downloading Mariadb $version"
    curl -sSL -o "$target" "https://downloads.mariadb.org/f/mariadb-${version}/bintar-linux-x86_64/mariadb-${version}-linux-x86_64.tar.gz/from/https%3A//archive.mariadb.org/?serve"
}

get_mariadb 10.1.44
get_mariadb 10.4.15

docker build -t $IMG_NAME - < Dockerfile
docker run --rm -it \
    -v "$PWD/cache:/cache:ro" \
    $IMG_NAME \
    bash -c 'for i in /cache/*.gz; do dbdeployer unpack --verbosity 0 $i; done; bash'
